WeighingManagementSystem/Weighing.App.Web/ViewModels/TerminalConfigurationViewModel.cs
using OanTech.Paging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Weighing.App.Web.ViewModels
{
    public class TerminalConfigurationViewModel
    {
        public int TerminalConfigurationId { get; set; }
        [Required]
        [Display(Name = "Terminal ID")]
        public string TerminalId { get; set; }
        [Required]
        [Display(Name = "Terminal Category")]
        public string TerminalCategory { get; set; }
        [Required]
        [Display(Name = "Terminal Group")]
        public Nullable<int> TerminalGroup { get; set; }
        [Required]
        [Display(Name = "Terminal Description")]
        public string TerminalDescription { get; set; }
        [Required]
        [Display(Name = "Terminal Location")]
        public string TerminalLocation { get; set; }
        [Required]
        [Display(Name = "Allergen")]
        public bool IsAllergen { get; set; }
        [Required]
        [Display(Name = "Active")]
        public bool IsActive { get; set; }
    }

    public class TerminalConfigurationViewPaging
    {
        public IPagingHelper Paging { get; set; }
        public List<TerminalConfigurationViewModel> Data { get; set; }
    }
}

WeighingManagementSystem/Weighing.App.Web/Controllers/TerminalConfigurationController.cs
using OanTech.Framework.OanTechHelper;
using OanTech.Paging;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Weighing.App.Web.Helper;
using Weighing.App.Web.ViewModels;
using Weighing.Entities;
using Weighing.Terminal.Models;
using Weighing.Setting.Logic;
using Weighing.Setting.Models;
using OanTech.Common;
using System.Collections.ObjectModel;

namespace Weighing.App.Web.Controllers
{
    public class TerminalConfigurationController : Controller
    {
        // GET: GeneralSetting
        OanTechHelper ent = new OanTechHelper(MyEntities.Terminal);
        OanTechHelper entS = new OanTechHelper(MyEntities.Setting);
        GeneralSettingLogic objSetting = new GeneralSettingLogic();

        [SessionAuthorize]
        public ViewResult Index(int? page, string filter, string cFilter, string sortKey, string sortDir, string cSortDir)
        {
            //DEFAULT
            if (sortKey == null && sortDir == null)
            {
                sortKey = ViewBag.SortKey = "TerminalId";                                               //yang harus diisi
                sortDir = "ASC";
            }

            //Page
            page = filter == null ? page : 1;
            int pageNumber = page ?? 1;
            int pageSize = 5;                                                                       //yang harus diisi

            //NEW OR CURRENT --> FILTER & SORT
            filter = filter == null ? cFilter : filter;
            sortDir = sortDir == null ? cSortDir : sortDir;

            //QUERY
            var query = from a in ent.Resolve<TerminalConfiguration>().AsQueryable()                       //yang harus dibikin
                        select new
                        {
                           TerminalId = a.TerminalId,
                           TerminalCategory = a.TerminalCategory,
                           TerminalGroup = a.TerminalGroup,
                            TerminalDescription = a.TerminalDescription,
                            TerminalLocation = a.TerminalLocation,
                            IsAllergen = a.IsAllergen,
                            IsActive = a.IsActive
                        };

            //CUSTOM FILTER
            if (!string.IsNullOrEmpty(filter))
            {
                query = query.Where(x => x.TerminalCategory.Contains(filter) || x.TerminalLocation.Contains(filter));           //yang harus ditentukan
            }

            //ORDER BY & TOOGLE SORT DIRECTION
            query = query.OrderByField(sortKey, sortDir == "ASC" ? true : false);

            //GET PAGING
            var pagingResult = query.ToPaging(pageNumber, pageSize);

            //Map to VIEW MODEL
            TerminalConfigurationViewPaging pagingList = new TerminalConfigurationViewPaging();
            pagingList.Paging = pagingResult;
            pagingList.Data = new List<TerminalConfigurationViewModel>();

            foreach (var item in pagingResult)
            {
                TerminalConfigurationViewModel data = new TerminalConfigurationViewModel();
                data.TerminalId = item.TerminalId;
                data.TerminalCategory = item.TerminalCategory;
                data.TerminalDescription = item.TerminalDescription;
                data.TerminalGroup = item.TerminalGroup;
                data.TerminalLocation = item.TerminalLocation;
                data.IsAllergen = item.IsAllergen;
                data.IsActive = item.IsActive;
                pagingList.Data.Add(data);
            }


            //Ga usah dirubah
            ViewBag.cSortDir = sortDir; //buat jaga kondisi sort 
            ViewBag.SortDir = sortDir == "ASC" ? "DESC" : "ASC";  //buat bolak balikin (Toogle)
            ViewBag.SortKey = sortKey;
            ViewBag.cFilter = filter;


            ViewBag.FormName = "Terminal Configuration";
            return View(pagingList);
        }

        [SessionAuthorize]
        public ActionResult Create()
        {

            ViewBag.FormName = "Terminal Configuration";
            ViewBag.FormDescription = "Ini form description";
            ViewBag.TerminalId = GetListTerminal();
            //ViewBag.TerminalCategory = new SelectList(objSetting.GetListTerminalCategory(), "GSKey", "GSValue");
            //ViewBag.TerminalGroup = new SelectList(objSetting.GetListTerminalGroup(), "GSKey", "GSValue");
            return View("Create");
        }

        private IEnumerable<SelectListItem> GetListTerminal()
        {
            Collection<SelectListItem> list = new Collection<SelectListItem>();
            var data = objSetting.GetListTerminalId();

            foreach (var item in data)
            {
                list.Add(new SelectListItem() { Text = item.GSValue, Value = item.GSKey });
            }
            return list.OrderBy(x => x.Text);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TerminalConfigurationViewModel model, string submit)
        {
            if (ModelState.IsValid)
            {
                //taruh logic Insert disini,
                TerminalConfiguration entSave = new TerminalConfiguration();
                entSave.TerminalId = model.TerminalId;
                entSave.TerminalCategory = model.TerminalCategory;
                entSave.TerminalGroup = model.TerminalGroup;
                entSave.TerminalDescription = model.TerminalDescription;
                entSave.TerminalLocation = model.TerminalLocation;
                entSave.IsAllergen = model.IsAllergen;
                entSave.IsActive = model.IsActive;
                ent.Resolve<TerminalConfiguration>().Add(entSave);
                ent.Save();
                return RedirectToAction("Index");
            }

            ViewBag.FormName = "Terminal Configuration";
            return View(model);
        }
    }
}

WeighingManagementSystem/Weighing.App.Web/Views/TerminalConfiguration/Create.cshtml
@model Weighing.App.Web.ViewModels.TerminalConfigurationViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
<div class="page-toolbar">

    <div class="page-toolbar-block">
		<div class="page-toolbar-title">@ViewBag.FormName</div>
        <div class="page-toolbar-subtitle">@ViewBag.FormDescription</div>
    </div>
	
	@* === WEBSITE PATH === *@
    @*<ul class="breadcrumb">
        <li><a href="#">@ViewBag.FormName</a></li>
        <li class="active">@ViewBag.ViewName</li>
    </ul>*@
	
	@* === BUTTON FORM === *@
    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save</button>
            <a class="btn btn-danger" href="@Url.Content("~/YourController/Index")"><i class="fa fa-power-off"></i> Cancel</a>
        </div>
    </div>
</div>
	


<div class="row">
    <div class="col-md-12">
        <div class="block">
            <div class="block-head">
                <h2>Add New @ViewBag.FormName</h2>
            </div>
            <div class="block-content controls">
            @using (Html.BeginForm()) 
            {
            @Html.AntiForgeryToken()
	
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.TerminalId, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.TerminalId, new SelectList(ViewBag.TerminalId as IEnumerable<SelectListItem>, "Value", "Text"), "Select One")
                        @Html.ValidationMessageFor(model => model.TerminalId, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.TerminalCategory, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        @Html.DropDownList("TerminalCategory", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TerminalCategory, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.TerminalGroup, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        @Html.DropDownList("TerminalGroup", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TerminalGroup, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.TerminalDescription, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.TerminalDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TerminalDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.TerminalLocation, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.TerminalLocation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TerminalLocation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.IsAllergen, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsAllergen)
                            @Html.ValidationMessageFor(model => model.IsAllergen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row-form">
		            <div class="col-md-3">
			            <strong>
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label" })
			            </strong>
		            </div>
                    <div class="col-md-9">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

		        @* === ADDITIONAL BUTTON (IF NEEDED) === *@
                <div class="row-form">
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> save</button>
                                </div>
                            </div>
        }
    </div>
        </div>
    </div>
</div>
}


@*This View is Auto Generate by OanTech - April 2017*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WeighingManagementSystem/Weighing.App.Web/Views/TerminalConfiguration/Index.cshtml
@using OanTech.Paging;
@model Weighing.App.Web.ViewModels.TerminalConfigurationViewPaging

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-toolbar">

    <div class="page-toolbar-block">
        <div class="page-toolbar-title">@ViewBag.FormName</div>
        <div class="page-toolbar-subtitle">@ViewBag.FormDescription</div>
    </div>

    @* === WEBSITE PATH === *@
    @*<ul class="breadcrumb">
            <li><a href="#">@ViewBag.FormName</a></li>
            <li class="active">@ViewBag.ViewName</li>
        </ul>*@

    @* === BUTTON FORM === *@
    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <a class="btn btn-primary" href="@Url.Content("~/TerminalConfiguration/Create")"><i class="fa fa-plus"></i> New</a>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-head">
                    <h2>@ViewBag.FormName Data</h2>
                </div>
                <div class="block-content np">
                    <br />
                    <table>
                        <tr>
                            @using (Html.BeginForm("Index", "TerminalConfiguration", FormMethod.Get))
                            {
                                <td>
                                    <div align="right">
                                        <p>
                                            Search: @Html.TextBox("Filter", ViewBag.cFilter as string)
                                            <input type="submit" value="Search" />
                                        </p>
                                    </div>
                                </td>
                            }
                        </tr>
                    </table>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th width="10%">
                                @Html.ActionLink("Terminal ID", "Index", new { sortKey = "TerminalId", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="10%">
                                @Html.ActionLink("Category", "Index", new { sortKey = "TerminalCategory", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="10%">
                                @Html.ActionLink("Group", "Index", new { sortKey = "TerminalGroup", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="20%">
                                @Html.ActionLink("Description", "Index", new { sortKey = "TerminalDescription", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="10%">
                                @Html.ActionLink("Location", "Index", new { sortKey = "TerminalLocation", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="10%">
                                @Html.ActionLink("Allergen", "Index", new { sortKey = "IsAllergen", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="10%">
                                @Html.ActionLink("Active", "Index", new { sortKey = "IsActive", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                            </th>
                            <th width="20%">
                                Action
                            </th>
                        </tr>

                        @foreach (var item in Model.Data)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TerminalId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TerminalCategory)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TerminalGroup)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TerminalDescription)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TerminalLocation)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsAllergen)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.TerminalConfigurationId }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.TerminalConfigurationId }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.TerminalConfigurationId })
                                </td>
                            </tr>
                        }
                    </table>
                    <div class="sp"></div>
                    <table>
                        <tr>
                            <td>
                                Page @(Model.Paging.PageCount < Model.Paging.PageNumber ? 0 : Model.Paging.PageNumber) of @Model.Paging.PageCount
                            </td>
                            <td>
                                <div align="right">
                                    @Html.PagingHelperPagination(Model.Paging, page => Url.Action("Index", new { page, sortKey = ViewBag.SortKey, cSortDir = ViewBag.cSortDir, cFilter = ViewBag.cFilter }))
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
}


@*This View is Auto Generate by OanTech - April 2017*@