WeighingManagementSystem/Weighing.App.Web/ViewModels/GeneralSettingViewModel.cs
using OanTech.Paging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Weighing.App.Web.ViewModels
{
    public class GeneralSettingViewModel
    {
        public long GeneralSettingId { get; set; }

        [Required]
        [Display(Name = "General Setting Code")]
        public string GSCode { get; set; }

        [Required]
        [Display(Name = "General Setting Key")]
        public string GSKey { get; set; }

        [Required]
        [Display(Name = "General Setting Value")]
        public string GSValue { get; set; }
    }

    public class GeneralSettingViewPaging
    {
        public IPagingHelper Paging { get; set; }
        public List<GeneralSettingViewModel> Data { get; set; }
    }
}

WeighingManagementSystem/Weighing.App.Web/Controllers/GeneralSettingController.cs
using OanTech.Framework.OanTechHelper;
using OanTech.Paging;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Weighing.App.Web.Helper;
using Weighing.App.Web.ViewModels;
using Weighing.Entities;
using Weighing.Setting.Models;
using OanTech.Common;
namespace Weighing.App.Web.Controllers
{
    public class GeneralSettingController : Controller
    {
        // GET: GeneralSetting
        OanTechHelper ent = new OanTechHelper(MyEntities.Setting);

        [SessionAuthorize]
        public ViewResult Index(int? page, string filter, string cFilter, string sortKey, string sortDir, string cSortDir)
        {
            //DEFAULT
            if (sortKey == null && sortDir == null)
            {
                sortKey = ViewBag.SortKey = "GSCode";                                               //yang harus diisi
                sortDir = "ASC";
            }

            //Page
            page = filter == null ? page : 1;
            int pageNumber = page ?? 1;
            int pageSize = 5;                                                                       //yang harus diisi

            //NEW OR CURRENT --> FILTER & SORT
            filter = filter == null ? cFilter : filter;
            sortDir = sortDir == null ? cSortDir : sortDir;

            //QUERY
            var query = from a in ent.Resolve<GeneralSetting>().AsQueryable()                       //yang harus dibikin
                        select new
                        {
                            GeneralSettingId = a.GeneralSettingId,
                            GSCode = a.GSCode,
                            GSKey = a.GSKey,
                            GSValue = a.GSValue
                        };

            //CUSTOM FILTER
            if (!string.IsNullOrEmpty(filter))
            {
                query = query.Where(x => x.GSCode.Contains(filter) || x.GSValue.Contains(filter));           //yang harus ditentukan
            }

            //ORDER BY & TOOGLE SORT DIRECTION
            query = query.OrderByField(sortKey, sortDir == "ASC" ? true : false);

            //GET PAGING
            var pagingResult = query.ToPaging(pageNumber, pageSize);

            //Map to VIEW MODEL
            GeneralSettingViewPaging pagingList = new GeneralSettingViewPaging();
            pagingList.Paging = pagingResult;
            pagingList.Data = new List<GeneralSettingViewModel>();

            foreach (var item in pagingResult)
            {
                GeneralSettingViewModel data = new GeneralSettingViewModel();
                data.GeneralSettingId = item.GeneralSettingId;
                data.GSCode = item.GSCode;
                data.GSKey = item.GSKey;
                data.GSValue = item.GSValue;
                pagingList.Data.Add(data);
            }


            //Ga usah dirubah
            ViewBag.cSortDir = sortDir; //buat jaga kondisi sort 
            ViewBag.SortDir = sortDir == "ASC" ? "DESC" : "ASC";  //buat bolak balikin (Toogle)
            ViewBag.SortKey = sortKey;
            ViewBag.cFilter = filter;


            ViewBag.FormName = "General Setting";
            return View(pagingList);
        }

        [SessionAuthorize]
        public ActionResult Create()
        {
            ViewBag.FormName = "INI FORM NAME";
            ViewBag.FormDescription = "Ini form description";
            return View(new GeneralSettingViewModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GeneralSettingViewModel model, string submit)
        {
            if (ModelState.IsValid)
            {
                //taruh logic Insert disini, 
                return RedirectToAction("Index");
            }

            ViewBag.FormName = "General Setting";
            return View(model);
        }
    }
}

WeighingManagementSystem/Weighing.App.Web/Views/GeneralSetting/Create.cshtml
@model Weighing.App.Web.ViewModels.GeneralSettingViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    <div class="page-toolbar">

        <div class="page-toolbar-block">
            <div class="page-toolbar-title">@ViewBag.FormName</div>
            <div class="page-toolbar-subtitle">@ViewBag.FormDescription</div>
        </div>

        @* === WEBSITE PATH === *@
        @*<ul class="breadcrumb">
                <li><a href="#">@ViewBag.FormName</a></li>
                <li class="active">@ViewBag.ViewName</li>
            </ul>*@

        @* === BUTTON FORM === *@
        <div class="page-toolbar-block pull-right">
            <div class="widget-info widget-from">
                <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                <a class="btn btn-danger" href="@Url.Content("~/GeneralSeting/Index")"><i class="fa fa-power-off"></i> Cancel</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-head">
                    <h2>Add New @ViewBag.FormName</h2>
                </div>
                <div class="block-content controls">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row-form">
                            <div class="col-md-3">
                                <strong>
                                    @Html.LabelFor(model => model.GeneralSettingId, htmlAttributes: new { @class = "control-label" })
                                </strong>
                            </div>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.GeneralSettingId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.GeneralSettingId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row-form">
                            <div class="col-md-3">
                                <strong>
                                    @Html.LabelFor(model => model.GSCode, htmlAttributes: new { @class = "control-label" })
                                </strong>
                            </div>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.GSCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.GSCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row-form">
                            <div class="col-md-3">
                                <strong>
                                    @Html.LabelFor(model => model.GSKey, htmlAttributes: new { @class = "control-label" })
                                </strong>
                            </div>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.GSKey, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.GSKey, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row-form">
                            <div class="col-md-3">
                                <strong>
                                    @Html.LabelFor(model => model.GSValue, htmlAttributes: new { @class = "control-label" })
                                </strong>
                            </div>
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.GSValue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.GSValue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @* === ADDITIONAL BUTTON (IF NEEDED) === *@
                        @*<div class="row-form">
                                <div class="col-md-3">
                                    <button class="btn btn-primary"><i class="fa fa-plus"></i> Add</button>
                                </div>
                            </div>*@
                    }
                </div>
            </div>
        </div>
    </div>
}


@*This View is Auto Generate by OanTech - April 2017*@

WeighingManagementSystem/Weighing.App.Web/Views/GeneralSetting/Index.cshtml
@using OanTech.Paging;
@model Weighing.App.Web.ViewModels.GeneralSettingViewPaging

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-toolbar">

    <div class="page-toolbar-block">
		<div class="page-toolbar-title">@ViewBag.FormName</div>
        <div class="page-toolbar-subtitle">@ViewBag.FormDescription</div>
    </div>
	
	@* === WEBSITE PATH === *@
    @*<ul class="breadcrumb">
        <li><a href="#">@ViewBag.FormName</a></li>
        <li class="active">@ViewBag.ViewName</li>
    </ul>*@
	
	@* === BUTTON FORM === *@
    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <a class="btn btn-primary" href="@Url.Content("~/GeneralSetting/Create")"><i class="fa fa-plus"></i> New</a>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
<div class="row">
    <div class="col-md-12">
        <div class="block">
            <div class="block-head">
                <h2>@ViewBag.FormName Data</h2>
            </div>
            <div class="block-content np">
                <br />
                <table>
                    <tr>
                        @using (Html.BeginForm("Index", "GeneralSetting", FormMethod.Get))
                        {
                            <td>
                                <div align="right">
                                    <p>
                                        Search: @Html.TextBox("Filter", ViewBag.cFilter as string)
                                        <input type="submit" value="Search" />
                                    </p>
                                </div>
                            </td>
                        }
                    </tr>
                </table>
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">
                            @Html.ActionLink("Codenya", "Index", new { sortKey = "GSCode", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            @Html.ActionLink("Key-nya", "Index", new { sortKey = "GSKey", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            @Html.ActionLink("Value-nya", "Index", new { sortKey = "GSValue", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            Action
                        </th>
                    </tr>

                    @foreach (var item in Model.Data)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.GSCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GSKey)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GSValue)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.GeneralSettingId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.GeneralSettingId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.GeneralSettingId })
                            </td>
                        </tr>
                    }
                </table>
				<div class="sp"></div>
                <table>
                    <tr>
                        <td>
                            Page @(Model.Paging.PageCount < Model.Paging.PageNumber ? 0 : Model.Paging.PageNumber) of @Model.Paging.PageCount
                        </td>
                        <td>
                            <div align="right">
                                @Html.PagingHelperPagination(Model.Paging, page => Url.Action("Index", new { page, sortKey = ViewBag.SortKey, cSortDir = ViewBag.cSortDir, cFilter = ViewBag.cFilter }))
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
}


@*This View is Auto Generate by OanTech - April 2017*@