WeighingManagementSystem/Weighing.App.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weighing.App.Web.Controllers
{
    public class BaseController : Controller
    {
        // GET: Base
        public ActionResult NotAuthorized()
        {
            return View();
        }

        public ActionResult ViewMessage()
        {
            return PartialView("_MessagePopUp");
        }
    }
}

WeighingManagementSystem/Weighing.App.Web/Views/Base/NotAuthorized.cshtml
@model Weighing.App.Web.ViewModels.GeneralSettingViewModel

@{
    ViewBag.Title = "Unauthorized Access";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    Html.AntiForgeryToken();
    <div class="page-toolbar">

        <div class="page-toolbar-block">
            <div class="page-toolbar-title">NOT AUTHORIZED</div>
            <div class="page-toolbar-subtitle">Sorry, you are not Autorized to access this page.</div>
        </div>
        @* === BUTTON FORM === *@
        <div class="page-toolbar-block pull-right">
            <div class="widget-info widget-from">
                <a class="btn btn-danger" href="javascript:history.go(-1)"><i class="fa fa-power-off"></i> Back</a>
                @Html.ActionLink("Lyubomir ", "ViewMessage", "Base", null, new { @class = "modal-link btn btn-success" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div style="width: 100%; height: 100%;" align="center">
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <img src="~/Content/img/NotAuthorized.jpg" alt="Not Authorized" align="middle">
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
}


@*This View is Auto Generate by OanTech - April 2017*@

WeighingManagementSystem/Weighing.App.Web/Views/Base/_MessagePopUp.cshtml
<div class="modal-body">
    @if (ViewBag.MessageType == "Error")
    {
        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span>
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.MessageType == "Warning")
    {
        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span>
            @ViewBag.Message
        </div>
    }
    else if (ViewBag.MessageType == "Success")
    {
        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span>
            @ViewBag.Message
        </div>
    }
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign"></span>
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </div>


    @*@using (Html.BeginForm("Lyubomir", "Home", FormMethod.Post))
    {
        <div class="row">
            &nbsp;
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="submit" id="approve-btn" class="btn btn-danger">Save</button>
            </div>
        </div>
    }*@
</div>


<script type="text/javascript">
    $(function () {
        $('#approve-btn').click(function () {
            $('#modal-container').modal('hide');
        });
    });
</script>