WeighingManagementSystem/WeighingManagementSystem.Web/Controllers/TemplateController.cs
using AccountManagement.Models;
using AutoMapper;
using OanTech.Framework.OanTechHelper;
using OanTech.Paging;
using OANTech.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OANTech.Web.Controllers
{
    public class TemplateController : Controller
    {
        OanTechHelper ent = new OanTechHelper(MyEntities.AccountManagement);
        // GET: Template
        public ActionResult InputOneColumn()
        {
            return View();
        }

        public ViewResult DataTable(int? page, string filter, string cFilter, string sortKey, string sortDir, string cSortDir)
        {
            



            ////PAGING DENGAN 1 Model

            ////Default Sort
            //if (sortKey == null && sortDir == null)
            //{
            //    sortKey = ViewBag.SortKey = "RoleName";
            //    sortDir = "ASC";
            //}

            ////Page, Filter & Sort Dir
            //page = filter == null ? page : 1;
            //int pageNumber = page ?? 1;
            //int pageSize = 5;

            //filter = filter == null ? cFilter : filter;
            //sortDir = sortDir == null ? cSortDir : sortDir;

            ////Query
            //var dataResult = ent.Resolve<Role>().GetQueryableQuery();
            //if (!String.IsNullOrEmpty(filter))
            //{
            //    dataResult = ent.Resolve<Role>().GetQueryableQuery().Where(x => x.RoleName.Contains(filter));
            //}

            ////Order by
            //dataResult = dataResult.OrderByField(sortKey, sortDir == "ASC" ? true : false);

            //ViewBag.cSortDir = sortDir; //buat jaga kondisi sort 
            //ViewBag.SortDir = sortDir == "ASC" ? "DESC" : "ASC";  //buat bolak balikin (Toogle)
            //ViewBag.SortKey = sortKey;
            //ViewBag.cFilter = filter;

            //return View(dataResult.ToPaging(pageNumber, pageSize));




            //DEFAULT
            if (sortKey == null && sortDir == null)
            {
                sortKey = ViewBag.SortKey = "RoleName";
                sortDir = "ASC";
            }

            //Page
            page = filter == null ? page : 1;
            int pageNumber = page ?? 1;
            int pageSize = 5;

            //NEW OR CURRENT --> FILTER & SORT
            filter = filter == null ? cFilter : filter;
            sortDir = sortDir == null ? cSortDir : sortDir;

            //QUERY
            var query = from a in ent.Resolve<Role>().AsQueryable()
                        select new
                        {
                            RoleId = a.RoleId,
                            RoleName = a.RoleName,
                            Date = a.DtCrt
                        };

            //CUSTOM FILTER
            if (!string.IsNullOrEmpty(filter))
            {
                query = query.Where(x => x.RoleName.Contains(filter));
            }

            //ORDER BY & TOOGLE SORT DIRECTION
            query = query.OrderByField(sortKey, sortDir == "ASC" ? true : false);

            //GET PAGING
            var pagingResult = query.ToPaging(pageNumber, pageSize);

            //Map to VIEW MODEL
            UserRoleViewPaging pagingList = new UserRoleViewPaging();
            pagingList.Paging = pagingResult;
            pagingList.Data = new List<UserRoleViewModel>();


            //pagingList.Data = pagingResult.Cast<UserRoleViewModel>().ToList();

            //var xx = pagingResult.Select(s => new { RoleId = s.RoleId, RoleName = s.RoleName }).ToList();
            //List<object> data = pagingResult.Cast<object>().ToList();


            //var listFiles = new List<UserRoleViewModel>();
            //listFiles = new BindingList<UserRoleViewModel>(pagingResult);



            ////pagingList.Data = data.ToList();

            ////pagingList.Data = new List<UserRoleViewModel>();

            ////EmployeeViewItem employeeViewItem = Mapper.Map<Employee, Employee>(employee);

            foreach (var item in pagingResult)
            {
                UserRoleViewModel data = new UserRoleViewModel();
                data.RoleId = item.RoleId;
                data.FirstName = item.RoleName;
                data.LastName = item.RoleName;
                data.BirthDate = item.Date;
                data.Email = item.RoleName;
                pagingList.Data.Add(data);
            }

            ViewBag.cSortDir = sortDir; //buat jaga kondisi sort 
            ViewBag.SortDir = sortDir == "ASC" ? "DESC" : "ASC";  //buat bolak balikin (Toogle)
            ViewBag.SortKey = sortKey;
            ViewBag.cFilter = filter;

            return View(pagingList);



            //var queryPaged = query.ToPaging(pageNumber, pageSize);

            //List<UserRoleViewModel> listData = new List<UserRoleViewModel>();
            //foreach (var item in queryPaged)
            //{
            //    UserRoleViewModel data = new UserRoleViewModel();
            //    data.RoleId = item.RoleId;
            //    data.FirstName = item.RoleName;
            //    data.LastName = item.RoleName;
            //    data.BirthDate = item.Date;
            //    data.Email = item.RoleName;
            //    listData.Add(data);
            //}

            //return View(queryPaged);
            //var vm = Mapper.Map<IEnumerable<queryPaged>, IEnumerable<UserRoleViewModel>>(queryPaged.ToArray());

            //datanya.listDataViewModel = query.ToPaging(pageNumber, pageSize).ToList();

            //ViewBag.cSortDir = sortDir; //buat jaga kondisi sort 
            //ViewBag.SortDir = sortDir == "ASC" ? "DESC" : "ASC";  //buat bolak balikin (Toogle)
            //ViewBag.SortKey = sortKey;
            //ViewBag.cFilter = filter;

            //return View(query.ToPaging(pageNumber, pageSize));

            //query = query.OrderByField(sortKey, sortDir == "ASC" ? true : false);

            //List<PagingUserViewModel> listData = new List<PagingUserViewModel>();
            //var result = query.ToPaging(pageNumber, pageSize)

            //PagingUserViewModel data = null;

            //foreach (var item in result)
            //{
            //    data = new PagingUserViewModel();
            //    data.RoleId = int.Parse(item.RoleId.ToString());
            //    data.FirstName = item.FirstName.ToString();
            //    data.LastName = item.LastName.ToString();
            //    data.BirthDate = DateTime.Parse(item.BirthDate.ToString());
            //    data.Email = item.Email.ToString();
            //    listData.Add(data);
            //}
            //return View(listData);
        }
    }
}

WeighingManagementSystem/WeighingManagementSystem.Web/Views/Template/DataTable - asli.cshtml
@model OanTech.Paging.IPagingHelper<AccountManagement.Models.Role>
@using OanTech.Paging;

@{
    ViewBag.Title = "DataTable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-toolbar">

    <div class="page-toolbar-block">
        <div class="page-toolbar-title">Lazy Loading Table</div>
    </div>

    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
            <button class="btn btn-primary"><i class="fa fa-cog"></i> Settings</button>
            <button class="btn btn-danger"><i class="fa fa-power-off"></i> Exit</button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="block">
            <div class="block-content">
                <h2><strong>Input</strong> Elements</h2>
            </div>
            <div class="block-content np">
                <table>
                    <tr>
                        <td></td>
                        <td>
                            <div align="right">
                                @using (Html.BeginForm("DataTable", "Template", FormMethod.Get))
                                {
                                    <div align="right">
                                        <p>
                                            Search: @Html.TextBox("Filter", ViewBag.cFilter as string)
                                            <input type="submit" value="Search" />
                                        </p>
                                    </div>
                                }
                            </div>
                        </td>
                    </tr>
                </table>
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">
                            @Html.ActionLink("Role Name", "DataTable", new { sortKey = "RoleName", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            @Html.ActionLink("Date", "DataTable", new { sortKey = "DtCrt", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        @*<th width="15%">
                            @Html.ActionLink("Birth Date", "DataTable", new { sortKey = "BirthDate", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="25%">
                            @Html.ActionLink("Email", "DataTable", new { sortKey = "Email", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>*@
                        <th width="20%">
                            Action
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RoleName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DtCrt)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.BirthDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>*@
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.RoleId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.RoleId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.RoleId })
                            </td>
                        </tr>
                    }
                </table>
                <table>
                    <tr>
                        <td>
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        </td>
                        <td>
                            <div align="right">
                                @Html.PagingHelperPagination(Model, page => Url.Action("DataTable", new { page, sortKey = ViewBag.SortKey, cSortDir = ViewBag.cSortDir, cFilter = ViewBag.cFilter }))
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

WeighingManagementSystem/WeighingManagementSystem.Web/Views/Template/DataTable.cshtml
@using OanTech.Paging;

@model  OANTech.Web.ViewModel.UserRoleViewPaging

@{
    ViewBag.Title = "DataTable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-toolbar">

    <div class="page-toolbar-block">
        <div class="page-toolbar-title">Lazy Loading Table</div>
    </div>

    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
            <button class="btn btn-primary"><i class="fa fa-cog"></i> Settings</button>
            <button class="btn btn-danger"><i class="fa fa-power-off"></i> Exit</button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="block">
            <div class="block-content">
                <h2><strong>Input</strong> Elements</h2>
            </div>
            <div class="block-content np">
                <table>
                    <tr>
                        @using (Html.BeginForm("DataTable", "Template", FormMethod.Get))
                        {
                            <td>
                                <div align="left">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        <input type="text" class="form-control datepicker" />
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div align="right">
                                    <p>
                                        Search: @Html.TextBox("Filter", ViewBag.cFilter as string)
                                        <input type="submit" value="Search" />
                                    </p>
                                </div>
                            </td>
                        }
                    </tr>
                </table>
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">
                            @Html.ActionLink("First Name", "DataTable", new { sortKey = "RoleName", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            @Html.ActionLink("Last Name", "DataTable", new { sortKey = "RoleName", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="15%">
                            @Html.ActionLink("Birth Date", "DataTable", new { sortKey = "Date", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="25%">
                            @Html.ActionLink("Email", "DataTable", new { sortKey = "RoleName", sortDir = ViewBag.SortDir, cFilter = ViewBag.cFilter })
                        </th>
                        <th width="20%">
                            Action
                        </th>
                    </tr>

                    @foreach (var item in Model.Data)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BirthDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.RoleId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.RoleId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.RoleId })
                            </td>
                        </tr>
                    }
                </table>
                <table>
                    <tr>
                        <td>
                            Page @(Model.Paging.PageCount < Model.Paging.PageNumber ? 0 : Model.Paging.PageNumber) of @Model.Paging.PageCount
                        </td>
                        <td>
                            <div align="right">
                                @Html.PagingHelperPagination(Model.Paging, page => Url.Action("DataTable", new { page, sortKey = ViewBag.SortKey, cSortDir = ViewBag.cSortDir, cFilter = ViewBag.cFilter }))
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

WeighingManagementSystem/WeighingManagementSystem.Web/Views/Template/InputOneColumn.cshtml
@{
    ViewBag.Title = "InputOneColumn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-toolbar">

    <div class="page-toolbar-block">
        <div class="page-toolbar-title">Input With 2 Column</div>
    </div>

    <div class="page-toolbar-block pull-right">
        <div class="widget-info widget-from">
            <button class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
            <button class="btn btn-primary"><i class="fa fa-cog"></i> Settings</button>
            <button class="btn btn-danger"><i class="fa fa-power-off"></i> Exit</button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="block">
            <div class="block-content">
                <h2><strong>Input</strong> Elements</h2>
            </div>
            <div class="block-content controls">
                <div class="row-form">
                    <div class="col-md-2"><strong>Name:</strong></div>
                    <div class="col-md-4"><input type="text" class="form-control" placeholder="Input Your Name" /></div>
                    <div class="col-md-2"><strong>Text Right:</strong></div>
                    <div class="col-md-4"><input type="text" class="form-control" value="input text value right" /></div>
                </div>
                <div class="row-form">
                    <div class="col-md-2"><strong>Address:</strong></div>
                    <div class="col-md-4"><input type="text" class="form-control" placeholder="Input Your Address" /></div>
                    <div class="col-md-2"><strong>Text Right:</strong></div>
                    <div class="col-md-4"><input type="text" class="form-control" value="input text value right" /></div>
                </div>
                <div class="row-form">
                    <div class="col-md-2"><strong>Tanggal</strong></div>
                    <div class="col-md-2">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" class="form-control datepicker" />
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                    <div class="col-md-2"><strong>Text Right:</strong></div>
                    <div class="col-md-4"><input type="text" class="form-control" value="input text value right" /></div>
                </div>
            </div>
        </div>
    </div>
</div>